Owner.create(username: "Joe", password: "test")
Owner.create(username: "Max", password: "test")
Book.create(title: "1984", author: "George Orwell", genre:"Fiction", published: 1949, condition: "used", book_type: "hardcover")
Book.create(title: "For Whom the Bell Tolls", author: "Ernest Hemingway", genre:"Fiction", published: 1940, condition: "used", book_type: "paperback")
Book.create(title: "Slaugherhouse-Five", author: "Kurt Vonnegut", genre:"Fiction", published: 1969, condition: "new", book_type: "hardcover")
Book.create(title: "Pride and Prejudice", author: "Jane Austen", genre:"Fiction", published: 1813, condition: "used", book_type: "paperback")
