john = Owner.create(username: "JohnSmith", password: "johnsmith", name: "John Smith", location: "Houston, TX")
max = Owner.create(username: "Max91", password: "mydogfido", name: "Max Hudson", location: "New York, NY")
ali = Owner.create(username: "Ali90", password: "iloveny", name: "Allison White", location: "New York, NY")
david = Owner.create(username: "David02", password: "leibowitz22", name: "David Leibowitz", location: "Los Angeles, CA")
erica = Owner.create(username: "EricaS", password: "redsox49", name: "Erica Sheffield", location: "Boston, MA")

orwell = Book.create(title: "1984", author: "George Orwell", genre:"Fiction", year: 1949, condition: "used", book_type: "Hardcover")
hemingway = Book.create(title: "For Whom the Bell Tolls", author: "Ernest Hemingway", genre:"War Novel", year: 1940, condition: "used", book_type: "Paperback")
vonnegut = Book.create(title: "Slaugherhouse-Five", author: "Kurt Vonnegut", genre:"Satire", year: 1969, condition: "new", book_type: "Hardcover")
austen = Book.create(title: "Pride and Prejudice", author: "Jane Austen", genre:"Romantic Novel", year: 1813, condition: "used", book_type: "Paperback")
macchiavelli = Book.create(title: "The Prince", author: "Niccolo Macchiavelli", genre:"Non-fiction", year: 1513, condition: "used", book_type: "Paperback")
kafka = Book.create(title: "The Metamorphosis", author: "Franz Kafka", genre:"Fantasy Fiction", year: 1813, condition: "used", book_type: "Paperback")
joyce = Book.create(title: "Ulysees", author: "James Joyce", genre:"Modernist Novel", year: 1922, condition: "new", book_type: "Hardcover")
fitzgerald = Book.create(title: "The Great Gatsby ", author: "F. Scott Fitzgerald", genre:"Tragedy", year: 1925, condition: "new", book_type: "Paperback")
rice = Book.create(title: "Interview with the Vampire ", author: "Anne Rice", genre:"Gothic Horror", year: 1976, condition: "used", book_type: "Hardcover")
melville = Book.create(title: "Moby Dick", author: "Herman Melville", genre:"Adventure Fiction", year: 1851, condition: "used", book_type: "Paperback")

john.books.push(orwell, hemingway)
max.books.push(vonnegut, austen)
ali.books.push(macchiavelli, kafka)
david.books.push(joyce, fitzgerald)
erica.books.push(rice, melville)
