Owner.create(username: "John01", password: "joesmithpassword", name: "John Smith", location: "Houston, TX")
Owner.create(username: "Max91", password: "mydogfido", name: "Max Hudson", location: "New York, NY")
Owner.create(username: "Ali90", password: "iloveny", name: "Allison White", location: "New York, NY")
Owner.create(username: "Dave02", password: "leibowitz22", name: "David Leibowitz", location: "Los Angeles, CA")
Owner.create(username: "EricaS", password: "redsox49", name: "Erica Sheffield", location: "Boston, MA")

Book.create(title: "1984", author: "George Orwell", genre:"Fiction", year: 1949, condition: "used", book_type: "hardcover")
Book.create(title: "For Whom the Bell Tolls", author: "Ernest Hemingway", genre:"War Novel", year: 1940, condition: "used", book_type: "paperback")
Book.create(title: "Slaugherhouse-Five", author: "Kurt Vonnegut", genre:"Satire", year: 1969, condition: "new", book_type: "hardcover")
Book.create(title: "Pride and Prejudice", author: "Jane Austen", genre:"Romantic Novel", year: 1813, condition: "used", book_type: "paperback")
Book.create(title: "The Prince", author: "Niccolo Macchiavelli", genre:"Non-fiction", year: 1513, condition: "used", book_type: "paperback")
Book.create(title: "The Metamorphosis", author: "Franz Kafka", genre:"Fantasy Fiction", year: 1813, condition: "used", book_type: "paperback")
Book.create(title: "Ulysees", author: "James Joyce", genre:"Modernist Novel", year: 1922, condition: "new", book_type: "hardcover")
Book.create(title: "The Great Gatsby ", author: "F. Scott Fitzgerald", genre:"Tragedy", year: 1925, condition: "new", book_type: "paperback")
Book.create(title: "Interview with the Vampire ", author: "Anne Rice", genre:"Gothic Horror", year: 1976, condition: "used", book_type: "hardcover")
Book.create(title: "Moby Dick", author: "Herman Melville", genre:"Adventure Fiction", year: 1851, condition: "used", book_type: "paperback")